targets:
  $default:
    builders:
      freezed:
        generate_for:
          include:
            - lib/**.dart
      json_serializable:
        options:
          explicit_to_json: true
        generate_for:
          include:
            - lib/**.dart
      riverpod_generator:
        generate_for:
          include:
            - lib/**.dart 